Add "return widget" to Layout's add_widget() method to make chaining easier
peterbrittain/asciimatics pull request #348
Opened 2022-03-21 18:41 UTC by cltrudeau

What does this implement/fix?
-----------------------------
One line change that adds "return widget" to the end of Layout's add_widget() method. This allows doing one-line layout and creation such as:

```
self.my_button = layout.add_widget(Button("My Button"), 1)
```

2022-03-21 18:51 UTC, cltrudeau commented
Hey Peter,

Something weird going on with the build. Fails just for Linux Py3.7. Works find in 3.6 and locally in 3.9. Doesn't seem to be complaining about my change, but something else.

Send me a comment if this is somehow my fault and I'll fix if I can.
...ct

2022-03-24 13:12 UTC, peterbrittain commented
Interesting.  Looks like a failure in pip... for a package we shouldn't need anymore!  Happy for you to remove the appveyor package as part of this MR.

2022-03-24 13:18 UTC, peterbrittain requested changes
When you said chaining, I thought you meant some way of calling add_widget again and again in the same line of code.  Got me wondering about a more functional API here...  But I think that would be a major overhaul and so not worth exploring here.

I like the way that this makes a mainline case easier...  Nice job!

Could you also tweak the UTs to test this in one case?

2022-03-24 13:18 UTC, peterbrittain commented on asciimatics/widgets/layout.py
>      def clear_widgets(self):
Can you please add a comment about the return to the function too?

2022-03-24 16:08 UTC, cltrudeau commented
> Interesting. Looks like a failure in pip... for a package we shouldn't need anymore! Happy for you to remove the appveyor package as part of this MR.

Only reference to that that I found was in a requirements.txt file. I removed it, but the problem is still happening.

Other changes have been made as requested.

2022-03-24 21:11 UTC, merged

2022-03-24 21:18 UTC, cltrudeau commented
Hey Peter,

Just curious when the next release will be with the changes to TextBox and other things. No hurry, I've copied the widget into another project, but when the release happens want to get rid of the local copy.

2022-03-24 21:43 UTC, peterbrittain commented
Soon.  I don't have any more major updates I want to get in now.

2022-03-26 09:16 UTC, peterbrittain commented
Sigh.  Travis support's fix didn't work...  Let's see what they come up with next.